// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzif8d5bexc2zdKKYnmkBlDCK2jWoE5C4',
    appId: '1:916380951554:web:62149db1d67aa918fef31b',
    messagingSenderId: '916380951554',
    projectId: 'movienest-5d1b4',
    authDomain: 'movienest-5d1b4.firebaseapp.com',
    storageBucket: 'movienest-5d1b4.firebasestorage.app',
    measurementId: 'G-8EBLJCNXZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Y447d0iutpiU4GpDlHLeZ-WScsEKH0s',
    appId: '1:916380951554:android:9765412ae29d2281fef31b',
    messagingSenderId: '916380951554',
    projectId: 'movienest-5d1b4',
    storageBucket: 'movienest-5d1b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjfp_PbzW7EGbx066ppnhJOrOeFx8ygEU',
    appId: '1:916380951554:ios:a7c551128b0048bcfef31b',
    messagingSenderId: '916380951554',
    projectId: 'movienest-5d1b4',
    storageBucket: 'movienest-5d1b4.firebasestorage.app',
    iosBundleId: 'com.example.movienest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzif8d5bexc2zdKKYnmkBlDCK2jWoE5C4',
    appId: '1:916380951554:web:6e3fbb22ba3cd9b4fef31b',
    messagingSenderId: '916380951554',
    projectId: 'movienest-5d1b4',
    authDomain: 'movienest-5d1b4.firebaseapp.com',
    storageBucket: 'movienest-5d1b4.firebasestorage.app',
    measurementId: 'G-Q0MHRF7NH4',
  );
}
